# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

---

name: Continuous Integration and Deployment

on:
   push:
     branches:
       - '*'
     paths:
       - 'src/*.xml'
       - '.github/workflows/*.yml'

env:
  IM_VERSION: '1.14.0.0'
  IM_VERSION_SHORT: '1E00'
  PDS_SCHEMA_URL: 'https://pds.nasa.gov/pds4/pds/v1/'
  REGRESSION_TEST_DIR: ${{ format('{0}/{1}/', github.workspace, 'test') }}
  # TODO - Have to hard-code this for now since Actions don't yet allow the use of env here.
  DEPLOY_DIR: ${{ format('{0}/{1}/{2}/{3}', github.workspace, 'build/development', github.sha, '1.14.0.0') }}
  # DEPLOY_DIR: ${{ format('{0}/{1}/', 'build/development', '8aab5f03e121d6be648377efc943edb0e71d49d4') }}

jobs:
  build:
    # TODO - Have to hard-code this for now since Actions don't yet allow the use of env here.
    name: 'LDD Build - v1.14.0.0'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate LDDs and Validate
        uses: NASA-PDS/gh-action-pds4-ldd@master
        with:
          datapath: ${{ env.DEPLOY_DIR }}
          pds4_im_version: ${{ env.IM_VERSION }}
          pds4_im_short_version: ${{ env.IM_VERSION_SHORT }}
          schemas: ${{ format('{0}/{1}', env.DEPLOY_DIR, '*.xsd') }}
          schematrons: ${{ format('{0}/{1}', env.DEPLOY_DIR, '*.sch') }}
          pds_schema_url: ${{ env.PDS_SCHEMA_URL }}
          test_dir: ${{ env.REGRESSION_TEST_DIR }}
          github_token: ${{ secrets.GITHUB_TOKEN }}


